#!/usr/bin/env python3
import asyncio
from tcp import Servidor
import re
from utils import *


def validar_nome(nome):
    print(nome)
    nome_b = nome.encode()
    return re.match(br'^[a-zA-Z][a-zA-Z0-9_-]*$', nome_b) is not None


def sair(conexao):
    print(conexao, 'conexão fechada')
    conexao.fechar()


def dados_recebidos(conexao, dados):
    if dados == b'':
        return sair(conexao)
    
    if dados.startswith(b'PING'):
        tratar_ping(conexao, dados)
    
    if dados.startswith(b'NICK'):
        new_nick = dados.split(b' ')[1].decode()
        if validar_nome(new_nick) == False:
            conexao.enviar(b'server 432 ' + conexao.get_nick().encode() + b' ' + new_nick.encode() + b' :Erroneous nickname')
        tratar_nick_valido(servidor, conexao, new_nick)

    print(conexao, dados)


def conexao_aceita(conexao):
    print(conexao, 'nova conexão')
    conexao.registrar_recebedor(dados_recebidos)
    servidor.adicionar_nick(conexao, conexao.get_nick())


servidor = Servidor(6667)
servidor.registrar_monitor_de_conexoes_aceitas(conexao_aceita)
asyncio.get_event_loop().run_forever()
